export const replicateFormFields = [
    {
        name: 'token',
        label: 'Replicate API Token',
        labelFR: 'Token API Replicate',
        type: 'password',
        required: true,
        placeholder: 'Enter your Replicate API token',
        placeholderFR: 'Entrez votre token API Replicate',
        helpText: 'You can find your API token in your Replicate account settings',
        helpTextFR: 'Vous pouvez trouver votre token API dans les paramètres de votre compte Replicate'
    }
];

export const replicatePlans = ['free', 'starter', 'pro', 'enterprise'];

export const replicateIndividualTools = [
    {
        name: 'Replicate - List Models',
        nameFR: 'Lister les Modèles Replicate',
        slug: 'replicate_list_models',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'List available models on the Replicate platform with pagination support.',
        descriptionFR: 'Lister les modèles disponibles sur la plateforme Replicate avec support de pagination.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Get Model',
        nameFR: 'Obtenir un Modèle Replicate',
        slug: 'replicate_get_model',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Get detailed information about a specific model on Replicate.',
        descriptionFR: 'Obtenir des informations détaillées sur un modèle spécifique sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Create Model',
        nameFR: 'Créer un Modèle Replicate',
        slug: 'replicate_create_model',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Create a new model on Replicate with specified configuration.',
        descriptionFR: 'Créer un nouveau modèle sur Replicate avec une configuration spécifiée.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Get Model Versions',
        nameFR: 'Obtenir les Versions du Modèle Replicate',
        slug: 'replicate_get_model_versions',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Get all versions of a specific model on Replicate.',
        descriptionFR: 'Obtenir toutes les versions d\'un modèle spécifique sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Get Model Version',
        nameFR: 'Obtenir une Version du Modèle Replicate',
        slug: 'replicate_get_model_version',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Get detailed information about a specific model version on Replicate.',
        descriptionFR: 'Obtenir des informations détaillées sur une version spécifique du modèle sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Create Prediction',
        nameFR: 'Créer une Prédiction Replicate',
        slug: 'replicate_create_prediction',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Create a new prediction on Replicate with specified input parameters.',
        descriptionFR: 'Créer une nouvelle prédiction sur Replicate avec des paramètres d\'entrée spécifiés.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Get Prediction',
        nameFR: 'Obtenir une Prédiction Replicate',
        slug: 'replicate_get_prediction',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Get the status and results of a specific prediction on Replicate.',
        descriptionFR: 'Obtenir le statut et les résultats d\'une prédiction spécifique sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - List Predictions',
        nameFR: 'Lister les Prédictions Replicate',
        slug: 'replicate_list_predictions',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'List all predictions with pagination support on Replicate.',
        descriptionFR: 'Lister toutes les prédictions avec support de pagination sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Cancel Prediction',
        nameFR: 'Annuler une Prédiction Replicate',
        slug: 'replicate_cancel_prediction',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Cancel a running prediction on Replicate.',
        descriptionFR: 'Annuler une prédiction en cours sur Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Run Prediction',
        nameFR: 'Exécuter une Prédiction Replicate',
        slug: 'replicate_run_prediction',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Run a prediction on Replicate using the simplified interface.',
        descriptionFR: 'Exécuter une prédiction sur Replicate en utilisant l\'interface simplifiée.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Generate Code',
        nameFR: 'Générer du Code Replicate',
        slug: 'replicate_generate_code',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Generate code using Replicate AI models with customizable parameters.',
        descriptionFR: 'Générer du code en utilisant les modèles IA Replicate avec des paramètres personnalisables.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Optimize Code',
        nameFR: 'Optimiser le Code Replicate',
        slug: 'replicate_optimize_code',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Optimize existing code for performance and readability using Replicate AI.',
        descriptionFR: 'Optimiser le code existant pour les performances et la lisibilité en utilisant l\'IA Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Debug Code',
        nameFR: 'Déboguer le Code Replicate',
        slug: 'replicate_debug_code',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Debug and fix code issues using Replicate AI models.',
        descriptionFR: 'Déboguer et corriger les problèmes de code en utilisant les modèles IA Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Generate Dockerfile',
        nameFR: 'Générer un Dockerfile Replicate',
        slug: 'replicate_generate_dockerfile',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Generate production-ready Dockerfiles using Replicate AI models.',
        descriptionFR: 'Générer des Dockerfiles prêts pour la production en utilisant les modèles IA Replicate.',
        formFields: replicateFormFields,
    },
    {
        name: 'Replicate - Generate Requirements',
        nameFR: 'Générer les Exigences Replicate',
        slug: 'replicate_generate_requirements',
        plans: replicatePlans,
        imageUrl: 'https://static.swiftask.ai/swiftaskagent/replicate-logo.png',
        description: 'Generate requirements.txt files by analyzing code dependencies using Replicate AI.',
        descriptionFR: 'Générer des fichiers requirements.txt en analysant les dépendances du code avec l\'IA Replicate.',
        formFields: replicateFormFields,
    },
];

export default replicateIndividualTools;